spring.application.name=demo

spring.grpc.server.port=9090

app.tarantool.host=localhost
app.tarantool.port=3301
app.tarantool.user=guest
app.tarantool.password=
app.tarantool.space=KV
app.tarantool.range-batch-size=5000
